In [46]:
# keras version : 2.4.3
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import pickle
import csv

In [47]:
loaded_model = keras.models.load_model('keras_model1')

In [48]:
loaded_model

In [49]:
df = pd.read_csv('training_dataset_remove_duplicates.csv')
scaler = pickle.load(open('scaler.pkl', 'rb'))
encoder = pickle.load(open('label_encoder.pkl', 'rb'))
num_row, num_col = df.shape

In [50]:
X = df.iloc[:,0:num_col-1]
Y = df.iloc[:, num_col-1]

In [51]:
X_scale = scaler.transform(X)

In [52]:
X_scale

array([[0.        , 0.        , 0.        , ..., 0.66666667, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.76190476, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.92857143, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.66666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.17391304, ..., 0.        , 0.        ,
        0.        ]])

In [53]:
test_data = scaler.transform(np.expand_dims(X.values[0], axis=0)) 

In [54]:
test_data

array([[0.        , 0.        , 0.        , ..., 0.66666667, 0.        ,
        0.        ]])

In [55]:
actual_result = np.argmax(loaded_model.predict(test_data).squeeze())

In [56]:
actual_result

7

In [ ]:
# ----------------- Start of scaler extraction ---------------------

In [73]:
dir(scaler)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_n_features',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_reset',
 '_validate_data',
 'copy',
 'data_max_',
 'data_min_',
 'data_range_',
 'feature_range',
 'fit',
 'fit_transform',
 'get_params',
 'inverse_transform',
 'min_',
 'n_features_in_',
 'n_samples_seen_',
 'partial_fit',
 'scale_',
 'set_params',
 'transform']

In [104]:
np.array(X.min(axis=0)) 

array([-110, -110, -110, ..., -110, -110, -110], dtype=int64)

In [92]:
1 / (X.max(axis=0) - X.min(axis=0))

AP_1       0.014286
AP_2       0.037037
AP_3       0.014493
AP_4       0.055556
AP_5       0.014493
             ...   
AP_1594    0.014493
AP_1595    0.076923
AP_1596    0.023810
AP_1597    0.018182
AP_1598    0.041667
Length: 1598, dtype: float64

In [110]:
scaler.scale_

array([0.01428571, 0.03703704, 0.01449275, ..., 0.02380952, 0.01818182,
       0.04166667])

In [112]:
#numpy array을 pandas dataframe으로 변환

# scale_csv = pd.DataFrame(scaler.scale_)
# scale_csv.to_csv('feature_scale_list.csv', index=False, header = False)

In [111]:
scale_csv

0
0     0.014286
1     0.037037
2     0.014493
3     0.055556
4     0.014493
...        ...
1593  0.014493
1594  0.076923
1595  0.023810
1596  0.018182
1597  0.041667

[1598 rows x 1 columns]

In [106]:
# This is formula to calculate feature scaling of original data!
(X.values[0] + 110) * scaler.scale_

array([0.        , 0.        , 0.        , ..., 0.66666667, 0.        ,
       0.        ])

In [93]:
min(X.values[:, 0]), max(X.values[:, 0])

(-110, -40)

In [91]:
scaler.scale_

array([0.01428571, 0.03703704, 0.01449275, ..., 0.02380952, 0.01818182,
       0.04166667])

In [84]:
scaler.data_min_

array([-110., -110., -110., ..., -110., -110., -110.])

In [ ]:
# ----------------- End of scaler extraction ---------------------

In [57]:
encoder.inverse_transform([actual_result])[0]

'REGION16'

In [66]:
# test for multiple data
temp = [np.argmax(r) for r in loaded_model.predict(scaler.transform(X.values[:125]))]

In [68]:
loaded_model.predict(scaler.transform(X.values[:125]))

array([[6.03412165e-09, 7.32807603e-05, 5.59416620e-08, ...,
        1.45262584e-06, 3.25777819e-06, 3.42793243e-08],
       [6.53559766e-08, 2.00696697e-04, 6.58540273e-07, ...,
        1.14015793e-05, 1.28268684e-05, 1.18432446e-07],
       [7.59505436e-09, 1.92482010e-04, 1.49754300e-07, ...,
        2.73033334e-06, 5.25398900e-06, 1.83263168e-07],
       ...,
       [3.85935067e-07, 8.18585977e-05, 1.18577864e-03, ...,
        4.30399465e-04, 4.51772612e-05, 2.99793464e-04],
       [5.56626922e-09, 1.11845984e-05, 1.76601548e-04, ...,
        3.93573246e-05, 3.14766839e-06, 3.39085309e-05],
       [1.50565320e-08, 9.97877240e-01, 1.42755103e-04, ...,
        1.98696299e-07, 1.59474675e-05, 1.62098164e-04]], dtype=float32)

In [59]:
encoder.inverse_transform(temp)

array(['REGION16', 'REGION16', 'REGION16', 'REGION16', 'REGION16',
       'REGION16', 'REGION3', 'REGION3', 'REGION3', 'REGION3', 'REGION3',
       'REGION3', 'REGION3', 'REGION3', 'REGION3', 'REGION3', 'REGION3',
       'REGION3', 'REGION3', 'REGION3', 'REGION3', 'REGION4', 'REGION4',
       'REGION4', 'REGION4', 'REGION4', 'REGION4', 'REGION4', 'REGION4',
       'REGION4', 'REGION4', 'REGION5', 'REGION4', 'REGION4', 'REGION4',
       'REGION4', 'REGION4', 'REGION4', 'REGION4', 'REGION5', 'REGION5',
       'REGION5', 'REGION5', 'REGION5', 'REGION5', 'REGION5', 'REGION5',
       'REGION5', 'REGION5', 'REGION5', 'REGION5', 'REGION5', 'REGION5',
       'REGION5', 'REGION5', 'REGION5', 'REGION5', 'REGION5', 'REGION5',
       'REGION4', 'REGION5', 'REGION5', 'REGION5', 'REGION5', 'REGION5',
       'REGION15', 'REGION15', 'REGION15', 'REGION15', 'REGION15',
       'REGION15', 'REGION15', 'REGION15', 'REGION15', 'REGION15',
       'REGION15', 'REGION15', 'REGION15', 'REGION15', 'REGION15',
 

In [60]:
# Convert from keras to TF Lite
converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model)
tflite_model = converter.convert()

INFO:tensorflow:Assets written to: C:\Users\User\AppData\Local\Temp\tmppsqwcb4l\assets


INFO:tensorflow:Assets written to: C:\Users\User\AppData\Local\Temp\tmppsqwcb4l\assets


In [61]:
# Save the model
# with open('model_tflite_version.tflite', 'wb') as f:
#     f.write(tflite_model)

In [62]:
# mapping between actual region and mapped region
le_name_mapping = dict(zip(encoder.transform(encoder.classes_), encoder.classes_))

In [63]:
le_name_mapping 

{0: 'REGION1',
 1: 'REGION10',
 2: 'REGION11',
 3: 'REGION12',
 4: 'REGION13',
 5: 'REGION14',
 6: 'REGION15',
 7: 'REGION16',
 8: 'REGION17',
 9: 'REGION18',
 10: 'REGION2',
 11: 'REGION3',
 12: 'REGION4',
 13: 'REGION5',
 14: 'REGION6',
 15: 'REGION7',
 16: 'REGION8',
 17: 'REGION9'}

In [115]:
# save label mapping result 

# with open('label_mapping.csv','w', newline="") as f:
#     w = csv.writer(f)
#     for key, value in le_name_mapping.items():
#        w.writerow([key, value])